language: cpp

compiler:
  - clang
  - gcc

before_install:
  # Always install g++4.9.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install: 
  # cmake
  - sudo apt-get install cmake

  # Always install g++4.8.1
  - sudo apt-get install -qq g++-4.9
  - sudo apt-get install -qq g++-4.9-multilib
  - if [ "$CXX" = "g++" ]; then export CMAKE_CXX_COMPILER="g++-4.9"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CMAKE_CXX_COMPILER="clang++-3.4"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  
  - export CXXFLAGS="-std=c++11 -stdlib=libc++"; fi

script:
  # - mkdir build 
  - cd build 
  - cmake .
  - make

after_script:
  - ./zupply_sample
  # - ctest .
  # - make valgrind

branches:
  only:
    - master