language: cpp

compiler:
  - clang
  - gcc

before_install:
  # Always install g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # clang 3.3
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install: 
  # cmake
  - sudo apt-get install cmake

script:
  # - mkdir build 
  - cd build 
  - cmake .
  - make

after_script:
  - ./zupply_sample
  # - ctest .
  # - make valgrind

branches:
  only:
    - master